# Project 3: Hashtable with Heapsort 
# Theory of Algorithms
# James Halladay
# Date: 10/9/2021
# 
# Description: This file will compile the program and 
# 			   serves as a test logger for the program.
# 


CC = g++
CFLAGS  = -g -Wall
RM = rm -f
LOG = ./logs/test.log
TESTHISTORY = ./logs/testHistory.log
MAINHISTORY = ./logs/mainHistory.log
HISTORY = ./logs/history.log



default: test



starttest:
	@echo "" > ${LOG}
	@echo "\nStarting Tests: `date`" >> ${LOG}


startmain:
	@echo "" > ${LOG}
	@echo "\nStarting Main: `date`" >> ${LOG}


runflag: 
	@touch runflag


hash.o: hash.cpp hash.h
	@echo "Compiling hash.cpp"
	@echo "\tCompiling hash.cpp: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) -c hash.cpp -o ./objects/hash.o >> ${LOG} 2>&1


heap.o: heap.cpp heap.h
	@echo "Compiling heap.cpp"
	@echo "\tCompiling heap.cpp: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) -c heap.cpp -o ./objects/heap.o >> ${LOG} 2>&1


assign3.o: assign3.cpp
	@echo "Compiling assign3.cpp"
	@echo "\tCompiling assign3.cpp: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) -c assign3.cpp -o ./objects/assign3.o >> ${LOG} 2>&1


main.o: main.cpp
	@echo "Compiling main.cpp"
	@echo "\tCompiling main.cpp: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) -c main.cpp -o ./objects/main.o >> ${LOG} 2>&1


test.o: test.cpp
	@echo "Compiling test.cpp"
	@echo "\tCompiling test.cpp: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) -c test.cpp -o ./objects/test.o >> ${LOG} 2>&1


utility.o: utility.cpp utility.h
	@echo "Compiling utility.cpp"
	@echo "\tCompiling utility.cpp: `date`" >> ${LOG} 2>&1
	-@$(CC) $(CFLAGS) -c utility.cpp -o ./objects/utility.o >> ${LOG} 2>&1


assign3.c: hash.o heap.o assign3.o utility.o
	@echo "Linking..."
	@echo "\tLinking Assign3: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) ./objects/assign3.o ./objects/hash.o ./objects/heap.o ./objects/utility.o -o assign3 >> ${LOG} 2>&1
	@echo "Built Assign3"
	@echo "\tBuilt Assign3: `date`" >> ${LOG}


main.c: hash.o heap.o main.o utility.o
	@echo "Linking..."
	@echo "\tLinking main: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) ./objects/main.o ./objects/hash.o ./objects/heap.o ./objects/utility.o -o main >> ${LOG} 2>&1
	@echo "Built Main"
	@echo "\tBuilt Main: `date`" >> ${LOG}


test.c: hash.o heap.o test.o utility.o  
	@echo "Linking..."
	@echo "\tLinking tests: `date`" >> ${LOG}
	-@$(CC) $(CFLAGS) ./objects/test.o ./objects/heap.o ./objects/hash.o ./objects/utility.o -o test >> ${LOG} 2>&1
	@echo "Built test"
	@echo "\tBuilt test: `date`" >> ${LOG}


test: starttest runflag test.c
	@rm runflag
	 
	@echo "\nRunning Tests: `date`\n" >> ${LOG}
	-@valgrind -q --leak-check=yes ./test >> ${LOG} 2>&1
	@echo "\nFinished Tests: `date` \n\n" >> ${LOG}

	@echo "\nRunning Tests: `date`\n" 
	-@./test
	@echo "\nFinished Tests: `date` \n"

	@cat ${LOG} >> ${TESTHISTORY}
	@cat ${LOG} >> ${HISTORY}



assign3: startmain runflag assign3.c
	@rm runflag
	@echo "\nRunning Assign3: `date`\n" >> ${LOG}
	-@valgrind -q --leak-check=yes ./assign3 "A Scandal in Bohemia.txt" sorted.txt >> ${LOG} 2>&1
	@echo "\nFinished Assign3: `date` \n\n" >> ${LOG} 2>&1

	@echo "\nRunning Assign3: `date`\n"
	-@./assign3 "A Scandal in Bohemia.txt" sorted.txt
	@echo "\nFinished Assign3: `date` \n"

	@cat ${LOG} >> ${MAINHISTORY}
	@cat ${LOG} >> ${HISTORY}


# -@valgrind -q --leak-check=yes ./main >> ${LOG} 2>&1
main: startmain runflag main.c
	@rm runflag

	@echo "\nRunning Main: `date`\n"
	-@./main
	@echo "\nFinished Main: `date` \n"

	@cat ${LOG} >> ${MAINHISTORY}
	@cat ${LOG} >> ${HISTORY}


clean: runflag
	@echo "" > ${LOG}
	@echo "\nCleaning up..."
	@echo "\nCleaning up: `date`\n" >> ${LOG}

	@$(RM) ./objects/*.o
	@$(RM) ./runflag
	@$(RM) ./main
	@$(RM) ./test

	@echo "Finished Cleaning\n"
	@echo "Finished Cleaning: `date`\n\n" >> ${LOG}

	@cat ${LOG} >> ${HISTORY}


clean_all: runflag
	@echo "\nCleaning up..."
 
	@$(RM) ./main
	@$(RM) ./test
	@$(RM) ./runflag
	@$(RM) ./objects/*.o
	@echo "" > ${LOG}
	@echo "" > ${TESTHISTORY}
	@echo "" > ${MAINHISTORY}
	@echo "" > ${HISTORY}

	@echo "Finished Cleaning\n"